apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: jenkins-agent-nodejs16
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: jenkins-agent-nodejs16
    labels:
      app: jenkins-agent-nodejs16
  spec:
    lookupPolicy:
      local: false
