exclude: '.terraform'
fail_fast: true

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks.git
  rev: v4.1.0
  hooks:
  - id: check-added-large-files
    args: ['--maxkb=5000']
  - id: check-byte-order-marker
  - id: check-case-conflict
  - id: check-json
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-yaml
    args: [--allow-multiple-documents, --unsafe]
  - id: detect-aws-credentials
    args: [--allow-missing-credentials]
  - id: detect-private-key
  - id: mixed-line-ending
    args: [--fix=lf]
  - id: pretty-format-json
    args: [--autofix, --indent=2, --no-ensure-ascii]
  - id: trailing-whitespace

- repo: https://github.com/awslabs/cfn-python-lint
  rev: v0.58.0
  hooks:
  - id: cfn-python-lint
    files: cfn-templates/.*\.(json|yml|yaml)$

- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.62.3
  hooks:
  - id: terraform_fmt

- repo: https://github.com/nichtraunzer/ods-pre-commit-hooks
  rev: v0.3.6
  hooks:
  - id: terraformcreatei2o
    files: (\.tf)$
  - id: terraformstackmoduleoutputs
    files: (\.tf)$

- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.62.3
  hooks:
  - id: terraform_fmt
  - id: terraform_docs

- repo: local
  hooks:
  - id: test
    name: make test
    description: Run integration tests.
    entry: make test
    language: system
    files: (\.tf|\.rb)$
    pass_filenames: false
    verbose: true

